version: '3'

services:
  openfga-import:
    depends_on: 
      openfga:
        condition: service_healthy 
    image: openfga/cli:v0.5.1
    container_name: openfga-import
    restart: "no"
    command: "store import --api-url http://openfga:8080 --file  /tmp/model.dsl"
    networks:
      - default
    volumes:
      - $PWD/openfga/openfga-model.dsl:/tmp/model.dsl

  keycloak-import:
    depends_on:
      openfga:
        condition: service_healthy 
      keycloak:
        condition: service_healthy
      openfga-import:
        condition: service_completed_successfully
    image: quay.io/keycloak/keycloak:${KC_VERSION}
    container_name: keycloak-import
    restart: "no"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - | 
        echo 'Waiting 5 secs...'
        sleep 5
        exec /opt/keycloak/init.sh
    environment:
      KEYCLOAK_URL: http://keycloak:8081
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password 
    volumes:        
      - $PWD/keycloak/init.sh:/opt/keycloak/init.sh
     
